os: linux
language: generic
sudo: required
dist: xenial
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - wget https://ci.swift.org/job/swift-PR-toolchain-Linux/247//artifact/branch-master/swift-PR-25685-247-ubuntu16.04.tar.gz -O /tmp/swift-PR-25685-247-ubuntu16.04.tar.gz
  - tar xzf /tmp/swift-PR-25685-247-ubuntu16.04.tar.gz -C $SWIFTENV_ROOT/versions/swift-PR-25685-247/
  - swiftenv global swift-PR-25685-247
script:
  - PYTHON_VERSION=2 swift test --enable-test-discovery
  - PYTHON_VERSION=3 swift test --enable-test-discovery
