name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Swift
        uses: YOCKOW/Action-setup-swift@master
        with:
          swift-version: '5.1'
      - name: Test (Python 2)
        env:
          PYTHON_VERSION: 2
        run: swift test --enable-test-discovery
      - name: Test (Python 3)
        env:
          PYTHON_VERSION: 3
        run: swift test --enable-test-discovery
